created a seed file and ran test [MP-29]
Mentor-Pathway/mentor-platform pull request #33
Opened 2022-11-03 15:58 UTC by BernardSimpson

feat: pathway seed
feat: user seed
feat: challenge
feat: user challenge

2022-11-04 16:57 UTC, BernardSimpson commented
feat: updated seed file by adding the PathChallenge to each challenge

2022-11-04 19:47 UTC, CraigNorford approved these changes

2022-11-04 21:32 UTC, BsBou requested changes
Every pathchallenge created has the same challenge_id, chall1.id, meaning the pathway will have 4 challenges, but they will all be the same.
The challenge_id needs to be different for each pathchallenge

2022-11-06 11:26 UTC, adrianHards commented
in addition to @BsBou's comments, I recommend reviewing our [style guide](https://craigdoescode.atlassian.net/wiki/spaces/MP/pages/13893859/Code+Style+Guide#Seeds) and making the appropriate adjustments.

2022-11-06 11:41 UTC, CraigNorford commented
Also merge with main main into your branch so the testing runs too

2022-11-09 13:41 UTC, BernardSimpson commented
Feat: updated seed file by adding loops to create pathways 
feat: updated seed file by adding loops to create challenges

2022-11-09 23:13 UTC, CraigDoesCode commented on db/seeds.rb
> +20.times do |i|
this part creates 20 pathways

2022-11-11 09:40 UTC, closed without merging