Final nav design
Mentor-Pathway/mentor-platform pull request #86
Opened 2023-01-13 18:03 UTC by BernardSimpson

fix/MP-115-navbar-changed-to-new-design

2023-01-14 11:32 UTC, adrianHards commented
![demo](https://user-images.githubusercontent.com/93719632/212469795-c182eee2-e56a-404e-88fd-6406120cd1e6.gif)

2023-01-14 11:39 UTC, adrianHards requested changes

2023-01-14 11:39 UTC, adrianHards commented on app/assets/stylesheets/application.css
> +nav {
place all code under nav rather than having two separate

2023-01-14 11:39 UTC, adrianHards commented on app/assets/stylesheets/application.css
> +.rounded-pill {
I need to hurry about and integrate SCSS, but eventually we should separate component styling (i.e. have them in their own SCSS file)

2023-01-15 09:52 UTC, CraigDoesCode approved these changes

2023-01-15 09:52 UTC, merged